# Generated by Django 3.2.22 on 2023-10-26 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 26, 12, 57, 13, 384106), help_text='Please select a date using d-m-y'),
        ),
    ]
