# Generated by Django 3.2.22 on 2023-10-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_userdetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='date',
            field=models.DateTimeField(help_text='Please select a date using d-m-y'),
        ),
    ]
