# Generated by Django 3.2.22 on 2023-10-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20231026_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.CharField(help_text='Please select a time', max_length=5),
        ),
    ]
