# Generated by Django 3.2.22 on 2023-10-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_userdetails_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='date',
            field=models.CharField(help_text='Please select a date using d-m-y', max_length=10),
        ),
    ]
