# Generated by Django 3.2.22 on 2023-10-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_userdetails_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='number_of_guests',
            new_name='guests',
        ),
    ]
