# Generated by Django 3.2.23 on 2024-01-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_userdetails_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
