# Generated by Django 3.2.23 on 2024-01-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_delete_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='customer',
            new_name='user',
        ),
    ]
